### ISSUE TITLE
VS2013: no import lib for leveldb.dll? 

### ISSUE THREAD

**Issue by remoe** [pelicanmapping/leveldb#2]
It doesn't generate a import library for the leveldb DLL. Do you use only the static build?

**Comment by jasonbeverage** [comment]
Yup, just the leveldb_static.lib should be alright.

**Comment by gwaldron** [comment]
There is an issue with the CMake where it always tries to link with the Release lib, even in Debug mode ... if you happen to see a way to resolve this issue that would be helpful :)
